extends Node

var ENEMIES = [
	{
		"image": load("res://assets/images/enemies/the_Cat_alph.png"),
		"max_in_swarm": 5,
		"health": 20,
		"damage": 10.0,
		"spawn_rate": 1,
		"title": "Микрокот",
		"text": "Микрокоты вообще не понимают, что тут происходит",
	},
	{
		"image": load("res://assets/images/enemies/pepega_1.png"),
		"max_in_swarm": 3,
		"health": 50,
		"damage": 30.0,
		"spawn_rate": 1,
		"title": "Пепега",
		"text": "Эти пепеги грустят - завали их",
	},
	{
		"image": load("res://assets/images/enemies/uganda.png"),
		"max_in_swarm": 30,
		"health": 1,
		"damage": 1.0,
		"spawn_rate": 0.2,
		"title": "Мемный Наклз",
		"text": "Толпа Наклзов отбилась от своей принцессы и ищет новую",
	},
	{
		"image": load("res://assets/images/enemies/bogdan.jpg"),
		"max_in_swarm": 1,
		"health": 120,
		"damage": 9.9,
		"spawn_rate": 0.2,
		"title": "Дядя Богдан",
		"text": "Дядя Богдан пришел за тобой",
	},
	{
		"image": load("res://assets/images/enemies/svidetel.png"),
		"max_in_swarm": 9,
		"health": 33,
		"damage": 3.0,
		"spawn_rate": 0.5,
		"title": "Свидетель из Фрязино",
		"text": "Они пришли засвидетельствовать фееричное поражение",
	},
	{
		"image": load("res://assets/images/enemies/GLAZZ.png"),
		"max_in_swarm": 20,
		"health": 9,
		"damage": 5.0,
		"spawn_rate": 0.4,
		"title": "Глазик",
		"text": "Их пришествее знаменует перепрохождение величайшей игры",
	},
	{
		"image": load("res://assets/images/enemies/tank.png"),
		"max_in_swarm": 1,
		"health": 90,
		"damage": 20.0,
		"spawn_rate": 0.5,
		"title": "Танк",
		"text": "Он едет. Но в отличии от тебя он не верит, так что результат предрешён",
	},
	{
		"image": load("res://assets/images/enemies/iyi.png"),
		"max_in_swarm": 9,
		"health": 19,
		"damage": 9.0,
		"spawn_rate": 1.0,
		"title": "ЪУЪ",
		"text": "Чем же недовольны эти котята?",
	},
	{
		"image": load("res://assets/images/enemies/head_crabik.png"),
		"max_in_swarm": 40,
		"health": 1,
		"damage": 1.0,
		"spawn_rate": 0.3,
		"title": "Головокраб",
		"text": "Не помешала бы монтировка под рукой",
	},
	{
		"image": load("res://assets/images/enemies/izbalolistttt.png"),
		"max_in_swarm": 1,
		"health": 80,
		"damage": 50.0,
		"spawn_rate": 0.5,
		"title": "Избиболист",
		"text": "Выглядит привычно, но что-то не так",
	},
		{
		"image": load("res://assets/images/enemies/izbalolistttt_dark.png"),
		"max_in_swarm": 1,
		"health": 160,
		"damage": 50.0,
		"spawn_rate": 0.5,
		"title": "Бибалист",
		"text": "Вот он, тайнственный чужеземец из иных миров",
	},
	
]
